kind:           Service
apiVersion:     v1

metadata:
    name:       miweb           # Es el nombre que se da de alta en el DNS

spec:
    type:       NodePort #ClusterIP
    ports:
        - port:         8080    # Este es el puerto que se abrir치 en IP del servicio (balanceo)
          targetPort:   80      # IP de backend... de los nginx
          nodePort:     30080
    
    # Este balanceador que se va a montar que tendr치 su propia IP
    # Abrir치 el puerto 8080 para atender peticiones que se mandar치 balanceadas
    # Al puerto 80 de QUIEN?
    
    selector:
        app:    nginx-miweb