kind:           Deployment
apiVersion:     apps/v1

metadata:
    name:       deployment-nginx

spec:
    replicas: 4
    
    selector:
        matchLabels:
            app:    nginx-miweb
    
    template:
        metadata:
            name:       pod-nginx
            labels:
                app:    nginx-miweb
        
        spec:
            containers: # Que se queden corriendo (servicios|demonios) NO SCRIPS
                -   # Contenedor de nginx
                    name:   nginx
                    image:  nginx:latest
                    ports:
                        - containerPort: 80
                    resources:
                        requests: # Declaración de minimos
                            memory: 300Mi
                            cpu:    500m
                        #limits:   # Aunque haya más, kub no le da mas
                        #    memory: 300Mi
                        #    cpu:    500m                        