kind:           Secret
apiVersion:     v1

metadata:
    name:       mis-secretos

data:
    usuario-bbdd: bHVjYXM=
    contrasena-bbdd: bWkgc3VwZXIgY29udHJhc2XDsWE=
---
kind:           Pod
apiVersion:     v1

metadata:
    name:       pod-secret
    labels:
        app:    nginx-miweb

spec:
    containers: # Que se queden corriendo (servicios|demonios) NO SCRIPS
        -   # Contenedor de nginx
            name:   nginx
            image:  nginx:latest
            ports:
                - containerPort: 80
            env:
                - name: VAR1
                  value: Este es el valor
                - name: USUARIO
                  valueFrom: 
                    secretKeyRef:
                        name: mis-secretos
                        key: usuario-bbdd
                - name: PASSWORD
                  valueFrom: 
                    secretKeyRef:
                        name: mis-secretos
                        key: contrasena-bbdd
            